communities/urls.py
from communities.views import (
                                CommunitiesView,
                                CommunityDetailView,
                                AllCommunities,
                                CommunityCreate,
                                CommunitiesCatsView,
                                CommunityItemView,
                                CommunityListView,
                                CommunityDetailReload,
                                GygView,
                                CommunityMembersView,
                            )
from django.conf.urls import url

urlpatterns = [
    url(r'^user/(?P<pk>\d+)/$', CommunitiesView.as_view(), name='communities'),
    url(r'^(?P<pk>\d+)/$', CommunityDetailView.as_view(), name='community_detail'),
    url(r'^reload/(?P<pk>\d+)/$', CommunityDetailReload.as_view(), name='community_detail_reload'),
    url(r'^all-communities/$', AllCommunities.as_view(), name='all_communities'),
    url(r'^add/$', CommunityCreate.as_view(), name="add_community"),
    url(r'^cat/(?P<order>\d+)/$',CommunitiesCatsView.as_view(), name="communities_cats"),
    url(r'^item/(?P<pk>\d+)/$', CommunityItemView.as_view(), name='community_item'),
    url(r'^list/(?P<pk>\d+)/$', CommunityListView.as_view(), name="community_item_list"),
    url(r'^gygyg/$', GygView.as_view(), name="community_ggg"),
    url(r'^(?P<pk>\d+)/members/$', CommunityMembersView.as_view(), name='community_members'),
]

tr/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView, RedirectView
from django.contrib.auth.decorators import login_required
from ckeditor_uploader import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include ('main.urls')),

    url(r'^logout/$', auth_views.LogoutView.as_view(template_name="account/logout.html"), name='logout'),
    url(r'^signup/$', TemplateView.as_view(template_name="main/auth.html"),
        name='signup'),
    url(r'^email-verification/$',
        TemplateView.as_view(template_name="account/email_verification.html"),
        name='email-verification'),
    url(r'^login/$', TemplateView.as_view(template_name="account/login.html"),
        name='login'),
    url(r'^password-reset/$',TemplateView.as_view(template_name="account/password_reset.html"),
        name='password-reset'),
    url(r'^password-reset/confirm/$',TemplateView.as_view(template_name="account/password_reset_confirm.html"),
        name='password-reset-confirm'),
     url(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        TemplateView.as_view(template_name="password_reset_confirm.html"),
        name='password_reset_confirm'),
    url(r'^password-change/$',TemplateView.as_view(template_name="account/password_change.html"),
        name='password-change'),

    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^rest-auth/registration/', include('rest_auth.registration.urls')),
    url(r'^account/', include('allauth.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^follows/', include('follows.urls')),
    url(r'^invitations/', include('invitations.urls')),
    url(r'^communities/', include('communities.urls')),
    url(r'^moderation/', include('moderation.urls')),
    url(r'^notifications/', include('notifications.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^frends/', include('frends.urls')),
    url(r'^chat/', include('chat.urls')),
    url(r'^gallery/', include('gallery.urls')),
    url(r'^article/', include('article.urls')),
    url(r'^goods/', include('goods.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

communities/models.py
from django.conf import settings
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.utils import timezone
from django.db.models import Q
from django.db.models import Count
from pilkit.processors import ResizeToFill, ResizeToFit
from communities.helpers import upload_to_community_avatar_directory, upload_to_community_cover_directory
from imagekit.models import ProcessedImageField
from moderation.models import ModeratedObject, ModerationCategory
from main.models import Item
from goods.models import Good


class CommunityCategory(models.Model):
    name = models.CharField(max_length=100, blank=False, null=False, verbose_name="Название")
    avatar = models.ImageField(blank=False, null=True, verbose_name="Аватар")
    order = models.IntegerField(default=0, verbose_name="Номер")

    def __str__(self):
        return 'Категория: ' + self.name

    class Meta:
        verbose_name="Категория сообществ"
        verbose_name_plural="Категории сообществ"


class CommunitySubCategory(models.Model):
    name = models.CharField(max_length=100, blank=False, null=False, verbose_name="Название")
    sudcategory = models.ForeignKey(CommunityCategory, on_delete=models.CASCADE, related_name='community_categories', verbose_name="Подкатегория сообщества")
    avatar = models.ImageField(blank=False, null=True, verbose_name="Аватар")
    order = models.IntegerField(default=0, verbose_name="Номер")

    def __str__(self):
        return 'ПодКатегория: ' + self.name

    class Meta:
        verbose_name="Подкатегория сообществ"
        verbose_name_plural="Подкатегории сообществ"


class Community(models.Model):
    moderated_object = GenericRelation(ModeratedObject, related_query_name='communities',verbose_name="Модерация")
    category = models.ForeignKey(CommunitySubCategory, on_delete=models.CASCADE, related_name='community_sub_categories', verbose_name="Подкатегория сообщества")
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='created_communities', null=False, blank=False, verbose_name="Создатель")
    name = models.CharField(max_length=settings.COMMUNITY_CATEGORY_TITLE_MAX_LENGTH, blank=False, null=False, verbose_name="Название" )
    description = models.CharField(max_length=300, null=True, verbose_name="Описание" )
    rules = models.TextField(max_length=100, null=True, verbose_name="Правила")
    avatar = ProcessedImageField(blank=False, null=True, format='JPEG',
                                 options={'quality': 90}, processors=[ResizeToFill(500, 500)],
                                 upload_to=upload_to_community_avatar_directory)
    cover = ProcessedImageField(blank=False, null=True, format='JPEG',
                                options={'quality': 90},
                                upload_to=upload_to_community_avatar_directory,
                                processors=[ResizeToFit(width=1024, upscale=False)])
    created = models.DateTimeField(default=timezone.now, editable=False, verbose_name="Создано")
    starrers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='favorite_communities', verbose_name="Подписчики")
    banned_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='banned_of_communities', verbose_name="Черный список")
    status = models.CharField(max_length=100, blank=True, null=True, verbose_name="статус-слоган")
    COMMUNITY_TYPE_PRIVATE = 'T'
    COMMUNITY_TYPE_PUBLIC = 'P'
    COMMUNITY_TYPES = (
        (COMMUNITY_TYPE_PUBLIC, 'Публичное'),
        (COMMUNITY_TYPE_PRIVATE, 'Приватное'),
    )
    type = models.CharField(choices=COMMUNITY_TYPES, default='P', max_length=2)
    invites_enabled = models.BooleanField(default=True, verbose_name="Разрешить приглашения")
    is_deleted = models.BooleanField(
        default=False,
        verbose_name="Удаленное"
    )

    class Meta:
        verbose_name = 'сообщество'
        verbose_name_plural = 'сообщества'

    @classmethod
    def create_community(cls, name, category, creator, type, avatar=None, description=None,
                            rules=None, invites_enabled=None):

        if type is Community.COMMUNITY_TYPE_PRIVATE and invites_enabled is None:
            invites_enabled = False
        else:
            invites_enabled = True

        community = cls.objects.create(name=name, creator=creator, avatar=avatar,
                                       description=description, type=type, rules=rules,
                                       invites_enabled=invites_enabled, category=category)

        CommunityMembership.create_membership(user=creator, is_administrator=True, is_moderator=False,
                                              community=community)

        community.save()
        return community

    @classmethod
    def is_user_with_username_member_of_community_with_name(cls, username, community_name):
        """"
        Есть ли пользователь в сообществе?
        """
        return cls.objects.filter(name=community_name, memberships__user__username=username).exists()

    @classmethod
    def is_user_with_username_administrator_of_community_with_name(cls, username, community_name):
        """"
        Администратор ли пользователь в сообществе?
        """
        return cls.objects.filter(name=community_name, memberships__user__username=username,
                                  memberships__is_administrator=True).exists()

    @classmethod
    def is_user_with_username_moderator_of_community_with_name(cls, username, community_name):
        """"
        Модератор ли пользователь в сообществе?
        """
        return cls.objects.filter(name=community_name, memberships__user__username=username,
                                  memberships__is_moderator=True).exists()

    @classmethod
    def is_user_with_username_banned_from_community_with_name(cls, username, community_name):
        """"
        Забанен ли пользователь в сообществе?
        """
        return cls.objects.filter(name=community_name, banned_users__username=username).exists()

    @classmethod
    def is_community_with_name_invites_enabled(cls, community_name):
        """"
        Нужно ли приглашение в сообщество?
        """
        return cls.objects.filter(name=community_name, invites_enabled=True).exists()

    @classmethod
    def is_community_with_name_private(cls, community_name):
        """"
        Приватное ли сообщество?
        """
        return cls.objects.filter(name=community_name, type='T').exists()

    @classmethod
    def community_with_name_exists(cls, community_name):
        """"
        Есть ли сообщество, не удаленное?
        """
        query = Q(name=community_name, is_deleted=False)
        return cls.objects.filter(query).exists()

    @classmethod
    def get_community_with_name_for_user_with_id(cls, community_name, user_id):
        """"
        Получаем сообщества для пользователя?
        """
        query = Q(name=community_name, is_deleted=False)
        query.add(~Q(banned_users__id=user_id), Q.AND)
        return cls.objects.get(query)

    @classmethod
    def search_communities_with_query(cls, query):
        """"
        Возврат списка сообществ при поиске
        """
        query = cls._make_search_communities_query(query=query)
        return cls.objects.filter(query)

    @classmethod
    def _make_search_communities_query(cls, query):
        """"
        Метод, получающий список сообществ при поиске
        """
        communities_query = Q(name__icontains=query)
        communities_query.add(Q(title__icontains=query), Q.OR)
        communities_query.add(Q(is_deleted=False), Q.AND)
        return communities_query

    @classmethod
    def get_trending_communities_for_user_with_id(cls, user_id, category_name=None):
        trending_communities_query = cls._make_trending_communities_query(category_name=category_name)
        trending_communities_query.add(~Q(banned_users__id=user_id), Q.AND)
        return cls._get_trending_communities_with_query(query=trending_communities_query)

    def get_posts(self, max_id=None):
        """
        Получить все посты сообщества
        """
        posts_query = Q(community_id=self.pk, is_deleted=False, status=Item.STATUS_PUBLISHED)
        exclude_reported_and_approved_posts_query = ~Q(moderated_object__status=ModeratedObject.STATUS_APPROVED)
        posts_query.add(exclude_reported_and_approved_posts_query, Q.AND)

        if max_id:
            posts_query.add(Q(id__lt=max_id), Q.AND)
        items = Item.objects.filter(posts_query)
        return items

    def get_goods(self, max_id=None):
        """
        Получить все посты пользователя
        """
        goods_query = Q(community_id=self.pk, is_deleted=False, status=Good.STATUS_PUBLISHED)
        exclude_reported_and_approved_goods_query = ~Q(moderated_object__status=ModeratedObject.STATUS_APPROVED)
        goods_query.add(exclude_reported_and_approved_goods_query, Q.AND)

        if max_id:
            goods_query.add(Q(id__lt=max_id), Q.AND)
        goods = Good.objects.filter(goods_query)
        return goods

    @classmethod
    def get_trending_communities(cls, category_name=None):
        """"
        Метод, получающий популярные сообщетсва
        """
        trending_communities_query = cls._make_trending_communities_query(category_name=category_name)
        return cls._get_trending_communities_with_query(query=trending_communities_query)

    @classmethod
    def _get_trending_communities_with_query(cls, query):
        return cls.objects.annotate(Count('memberships')).filter(query).order_by(
            '-memberships__count', '-created')

    @classmethod
    def _make_trending_communities_query(cls, category_name=None):
        trending_communities_query = Q(type=cls.COMMUNITY_TYPE_PUBLIC, is_deleted=False)
        if category_name:
            trending_communities_query.add(Q(categories__name=category_name), Q.AND)

communities/forms.py
from communities.models import Community
from django import forms


class CommunityForm(forms.ModelForm):

	class Meta:
		model = Community
		fields = [	'name',
					'type',
					'category',
					'id',
				]

communities/templates/community/forum.html
<div class="media mt-4">
    <div class="media-body">
        <h4 class="content-color-primary mb-0">Обсуждения </h4>
    </div>
    <a href="" class="">
        Все
    </a>
</div>
<br>
<ul class="list-group border-bottom list-group-flush">
    <li class="list-group-item link-media">
        <a href="" class="media">
            <div class="media-body">
                <h6 class="my-0 content-color-primary">20-11-2018</h6>
                <p class="small mb-2">New York, US</p>
                <p>Musical night festival seasons, Drama and comedy cultural family show.</p>
            </div>
        </a>
    </li>
</ul>

communities/templates/community/item.html
{% load staticfiles humanize liked_user %}

<span class="text-hide-xs">
  {% if object.get_previous_by_created %}
    <span class="prev_item" style="">
      <img style="width: 50px;" src="{% static 'images/icons/right-24px.svg' %}" />
    </span>
  {% endif %}
  {% if object.get_next_by_created %}
    <span class="next_item" style="">
      <img style="width: 50px;" src="{% static 'images/icons/left-24px.svg' %}" />
    </span>
  {% endif %}
</span>
<span class="item_fullscreen_hide">
  <img style="width:35px" src="{% static 'images/icons/close-24px.svg' %}" />
</span>

{% if object.post %}
<div class="mb-4 infinite-item" item-id="{{ object.uuid }}">
  {% include 'generic/community/post_detail.html' %}
</div>
{% endif %}

{% if object.article %}
<div class="mb-4 infinite-item" item-id="{{ object.uuid }}">
    {% include 'generic/community/article.html' with article=article  %}
</div>
{% endif %}

  {% if object.get_previous_by_created %}
    <script>
    	$('.prev_item').on('click', function () {
    		 $('#item_loader').html('').load("{% url 'community_item' pk=object.get_previous_by_created.pk %}");
    	});
    </script>

   {% endif %}
   {% if object.get_next_by_created %}

    <script>
      $('.next_item').on('click', function () {
    		 $('#item_loader').html('').load("{% url 'community_item' pk=object.get_next_by_created.pk %}");
    	});
    </script>
    {% endif %}

<script>
  $('.item_fullscreen_hide').on('click', function () {
  	 $('.item_fullscreen').hide();
  	 $('#item_loader').empty();
  });
</script>

communities/templates/community/list.html
{% load staticfiles humanize %}
<style>
.reaction_window {
  opacity: 0;
visibility: hidden;
position: absolute;
bottom: 25px;
margin-bottom: 10px;
display: flex;
transition: 0.5s;
}
.reaction_window:hover {
    z-index: 10;
    opacity: 1;
    visibility: visible;
    background: #D6DAE1;
    color: black;
}
.react_btn:hover~.reaction_window{
    z-index: 10;
    opacity: 1;
    visibility: visible;
    background: #D6DAE1;
    color: black;
}
</style>

{% if object_list %}

<div class="infinite-container">
  <div class="stream-update">
    <a href=""><span class="new-posts"></span> Загрузить новые записи</a>
  </div>

  <span class="stream">
    <div class="card mb-4 item_fullscreen" style="display:none">
      <div id="item_loader" style="margin-top:30px;position: relative;"></div>
    </div>

    {% if object.article %}
        {% include 'generic/community/article.html' with article=article %}
    {% endif %}

    {% if object.post %}
      {% include 'generic/community/post.html' with post=post  %}
    {% endif %}

    {% for object in object_list %}

      {% if object.article %}
          {% include 'generic/community/article.html' with article=article  %}
      {% endif %}

      {% if object.post %}
          {% include 'generic/community/post.html' with post=post  %}
      {% endif %}

    {% endfor %}
    <div class="load col-12 col-md-12" >
      {% if page_obj.has_next %}
        <a style="display:flex;justify-content:center;" class="infinite-more-link" href="{% url 'community_item_list' community.pk %}?page={{ page_obj.next_page_number }}">
          <img src="{% static 'images/loading.gif' %}">
        </a>
      {% endif %}

    </div>

  </span>
</div>
{% else %}
<h6>  Пока ничего нет...</h6>
{% endif %}

<script defer src="{% static 'scripts/item_script.js' %}" type="text/javascript"></script>

communities/templates/community/membersheeps.html
{% load staticfiles humanize %}

{% if membersheeps %}
<div class="media">
    <div class="media-body">
      <h4 class="content-color-primary mb-0">Подписчики </h4>

    </div>
    <a href="{% url 'community_members' pk=object.pk %}" class="">
      Все
    </a>
</div>
<br>
{% for object in membersheeps %}
<div class="card mb-2">
    <div class="card-body">
        <div class="media">
          <figure>
            {% if object.user.profile.avatar %}
              <img src="{{ object.user.profile.avatar.url }}" style="border-radius:50px;width:50px;" alt="image">
            {% else %}
              <img src="{% static 'images/user.png' %}" alt="image" style="border-radius:50px;width:50px;">
            {% endif %}
          </figure>
          <div class="media-body">
            <a href="{% url 'user' pk=object.user.pk %}" class="ajax">
              <h6 class="my-0 mt-1">{{ object.user.get_full_name }}</h6>
            </a>
            {% if object.user.get_online %}
              <p class="text-success">В сети</p>
            {% else %}
              <p class="small">Был(а) {{ object.user.last_activity|naturaltime }}</p>
            {% endif %}
          </div>
        </div>
    </div>
</div>
{% endfor %}

{% endif %}

communities/templates/community/new_post.html
{% load staticfiles %}

{% if staff %}
 <div class="card mb-4" style="border:1px solid rgba(0, 0, 0, 0.125);">
   <form action="" id="COMM-POST" method="post" enctype="multipart/form-data">
     {% csrf_token %}
     <div class="card-body p-0">
         <textarea name="text" id="id_text" class="id_text form-control bg-light-secondary border-0" rows="2" placeholder="Что у Вас нового?"></textarea>
     </div>
     <div class="card-footer border-top">
         <div class="row">
             <div class="col" style="display: flex;">
                 <a title="Статья"
                       class="btn btn-link btn-sm text-secondary"
                       id="community_article_add">
                       <img style="width:22px;" src="{% static 'images/icons/post_add-24px.svg' %}" />
                 </a>
                <div class="dropdown">
                 <a title="Изображение"
                       id="dropdown_image"
                       class="btn btn-link btn-sm text-secondary"
                       data-toggle="dropdown"
                       aria-haspopup="true"
                       aria-expanded="false">
                       <img style="width:22px;" src="{% static 'images/icons/camera_alt-24px.svg' %}" />
                  </a>
                  <div class="dropdown-menu dropdown-menu-top" aria-labelledby="dropdown_image">
                    <a id="images_upload" class="dropdown-item">Загрузить изображение</a>
                    <a id="gallery" class="dropdown-item">Мои изображения</a>
                    <a id="" class="dropdown-item">Использовать ссылку</a>
                  </div>
                </div>
               <div class="dropdown">
                 <a title="Еще"
                         class="btn btn-link btn-sm text-secondary"
                         id="dropdown_more"
                         data-toggle="dropdown"
                         aria-haspopup="true"
                         aria-expanded="false">
                         <img style="width:22px;" src="{% static 'images/icons/attach_file-24px.svg' %}" />
                 </a>
                 <div class="dropdown-menu dropdown-menu-top" aria-labelledby="dropdown_more">
                   <a id="doc" class="dropdown-item">Документ</a>
                   <a id="good" class="dropdown-item">Товар</a>
                   <a id="question" class="dropdown-item">Опрос</a>
                 </div>
               </div>
             </div>

             <div class="col-auto ">
                <img style="width:22px" id="settings" src="{% static 'images/icons/settings_applications-24px.svg' %}" />
                 <button type="submit" class="btn btn-rounded btn-sm text-uppercase pl-3">
                   <span class="text-hide-xs">Опубликовать</span>
                   <a>
                     <img style="width:25px;color:white" src="{% static 'images/icons/send-24px.svg' %}" />
                    </a>
                 </button>
             </div>
         </div>
        <span class="add_board">
         <div id="for_images_upload" style="display:none;margin:10px"></div>
         <div id="for_gallery" style="display:none">gallery</div>
         <div id="for_doc" style="display:none;margin:10px">doc</div>
         <div id="for_good" style="display:none;margin:10px">good</div>
         <div id="for_question" style="display:none;margin:10px">question</div>
         <div id="for_settings" style="display:none;margin:10px">
           <div class="custom-control custom-checkbox">
               <input type="checkbox" checked name="comments_enabled" id="id_comments_enabled" class="custom-control-input">
               <label class="custom-control-label" for="id_comments_enabled">
                   Комментарии включены
               </label>
           </div>
           <div class="custom-control custom-checkbox">
               <input type="checkbox" id="item_mute" class="custom-control-input">
               <label class="custom-control-label" for="item_mute">
                   Не отправлять уведомления
               </label>
           </div>
           <div class="form-group ">
             <label>статус</label>
             <select class="form-control" id="id_status" name="status" data-live-search="true" tabindex="-1" aria-hidden="true">
               <option value="P" checked>Опубликовано</option>
               <option value="D">Отложено</option>
             </select>
           </div>
         </div>
        </span>
     </div>
   </form>
 </div>

 <div class="card mb-4 article_fullscreen" style="display:none">
   <div id="article_loader" style="margin-top:30px"></div>
 </div>
{% endif %}

<script>
$('#images_upload').on('click', function () {
	 $('#for_images_upload').show();
});
$('#settings').on('click', function () {
	 $('#for_settings').show();
});
$('#gallery').on('click', function () {
	 $('#for_gallery').show();
});
$('#doc').on('click', function () {
	 $('#for_doc').show();
});
$('#good').on('click', function () {
	 $('#for_good').show();
});
$('#question').on('click', function () {
	 $('#for_question').show();
});
</script>
<script>
	$( "#community_article_add" ).click(function(){
		$('#article_loader').html('').load("{% url 'article_add_community' object.pk %}"); 
		$('.article_fullscreen').show();
	})
</script>

<script>
    var frm_post = $('#COMM-POST');
    frm_post.submit(function() {
        $.ajax({
            type: frm_post.attr('method'),
            url: "{% url 'post_add_community' object.pk %}",
            data: frm_post.serialize(),
            success: function (data) {
              $(".stream").prepend(data);
              $(".id_text").val("");
              $(".add_board #for_images_upload").hide();
              $(".add_board #for_gallery").hide();
              $(".add_board #for_doc").hide();
              $(".add_board #for_good").hide();
              $(".add_board #for_question").hide();
              $(".add_board #for_settings").hide();
              $.toast({
                  heading: '{{ request.user.first_name }}',
                  text: 'Запись успешно создана!',
                  showHideTransition: 'fade',
                  icon: 'success'
              })
            },
            error: function(data) {
              $.toast({
                  heading: '{{ request.user.first_name }}',
                  text: 'Для публикации записи нужно написать что-нибудь и/или вставить изображение(ия)',
                  showHideTransition: 'fade',
                  icon: 'error'
              })
            }

        });
        return false;
    });
</script>
<script>
  var textarea = document.querySelector('textarea');
textarea.addEventListener('keyup', function(){
  if(this.scrollTop > 0){
    this.style.height = this.scrollHeight + "px";
  }
});
</script>