article/urls.py
from article.views import (
                            ArticleView,
                            ArticleUserCreate,
                            ArticleNewView,
                            ArticleDetailView,
                            ArticleCommunityCreate,
                        )
from django.conf.urls import url


urlpatterns = [
    url(r'^$', ArticleView.as_view(), name='articles'),
    url(r'^add/$', ArticleUserCreate.as_view(), name="article_add_user"),
    url(r'^add_community/(?P<pk>\d+)/$', ArticleCommunityCreate.as_view(), name="article_add_community"),
    url(r'^new/(?P<uuid>[0-9a-f-]+)/$', ArticleNewView.as_view(), name='article_new'),
    url(r'^detail/(?P<uuid>[0-9a-f-]+)/$', ArticleDetailView.as_view(), name='article_detail'),
]

tr/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView, RedirectView
from django.contrib.auth.decorators import login_required
from ckeditor_uploader import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include ('main.urls')),

    url(r'^logout/$', auth_views.LogoutView.as_view(template_name="account/logout.html"), name='logout'),
    url(r'^signup/$', TemplateView.as_view(template_name="main/auth.html"),
        name='signup'),
    url(r'^email-verification/$',
        TemplateView.as_view(template_name="account/email_verification.html"),
        name='email-verification'),
    url(r'^login/$', TemplateView.as_view(template_name="account/login.html"),
        name='login'),
    url(r'^password-reset/$',TemplateView.as_view(template_name="account/password_reset.html"),
        name='password-reset'),
    url(r'^password-reset/confirm/$',TemplateView.as_view(template_name="account/password_reset_confirm.html"),
        name='password-reset-confirm'),
     url(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        TemplateView.as_view(template_name="password_reset_confirm.html"),
        name='password_reset_confirm'),
    url(r'^password-change/$',TemplateView.as_view(template_name="account/password_change.html"),
        name='password-change'),

    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^rest-auth/registration/', include('rest_auth.registration.urls')),
    url(r'^account/', include('allauth.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^follows/', include('follows.urls')),
    url(r'^invitations/', include('invitations.urls')),
    url(r'^communities/', include('communities.urls')),
    url(r'^moderation/', include('moderation.urls')),
    url(r'^notifications/', include('notifications.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^frends/', include('frends.urls')),
    url(r'^chat/', include('chat.urls')),
    url(r'^gallery/', include('gallery.urls')),
    url(r'^article/', include('article.urls')),
    url(r'^goods/', include('goods.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from django.utils import timezone
from pilkit.processors import ResizeToFit, ResizeToFill
from ckeditor_uploader.fields import RichTextUploadingField
from django.conf import settings
from imagekit.models import ProcessedImageField
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from django.contrib.postgres.indexes import BrinIndex
from main.models import Item


class Article(Item):
    title = models.CharField(max_length=100, blank=False, null=False, verbose_name="Заголовок" )
    g_image = ProcessedImageField(verbose_name='Главное изображение', blank=False, format='JPEG',
                                 options={'quality': 80}, processors=[ResizeToFill(1024, 700)],
                                 upload_to='articles/%Y/%m/%d')
    content = RichTextUploadingField(config_name='default',
                                      external_plugin_resources=[(
                                          'youtube',
                                          '/static/ckeditor_plugins/youtube/youtube/',
                                          'plugin.js',
                                          )],
                                      )


    @classmethod
    def create_article(cls, creator, community=None, g_image=None, content=None,
                    created=None, is_draft=False, status= None, comments_enabled=None ):

        article = Article.objects.create(
                                            creator=creator,
                                            content=content,
                                            g_image=g_image,
                                            community=community,
                                            comments_enabled=comments_enabled,
                                        )

        channel_layer = get_channel_layer()
        payload = {
                "type": "receive",
                "key": "additional_post",
                "actor_name": article.creator.get_full_name()
            }
        async_to_sync(channel_layer.group_send)('notifications', payload)
        return article


    class Meta:
        ordering=["-created"]
        verbose_name="статья"
        verbose_name_plural="статьи"

    def __str__(self):
        return self.creator.get_full_name()

article/forms.py
from article.models import Article
from django import forms


class ArticleForm(forms.ModelForm):

	class Meta:
		model = Article
		fields = ['title', 'content', 'g_image', 'comments_enabled']

article/views.py
from django.views.generic.base import TemplateView
from article.forms import ArticleForm
from users.models import User
from django.template.loader import render_to_string
from article.models import Article
from django.urls import reverse_lazy
from django.http import HttpResponse, HttpResponseBadRequest
from generic.mixins import CategoryListMixin
from communities.models import Community


class ArticleView(TemplateView):
    template_name="articles.html"


class ArticleNewView(CategoryListMixin, TemplateView):
    model=Article
    template_name="article.html"

    def get(self,request,*args,**kwargs):
        self.article = Article.objects.get(uuid=self.kwargs["uuid"])
        self.article.views += 1
        self.article.save()
        return super(ArticleNewView,self).get(request,*args,**kwargs)

    def get_context_data(self,**kwargs):
        context=super(ArticleNewView,self).get_context_data(**kwargs)
        context["object"]=self.article
        return context

class ArticleDetailView(CategoryListMixin, TemplateView):
    model=Article
    template_name="article_detail.html"

    def get(self,request,*args,**kwargs):
        self.article = Article.objects.get(uuid=self.kwargs["uuid"])
        self.article.views += 1
        self.article.save()
        return super(ArticleDetailView,self).get(request,*args,**kwargs)

    def get_context_data(self,**kwargs):
        context=super(ArticleDetailView,self).get_context_data(**kwargs)
        context["object"]=self.article
        return context


class ArticleUserCreate(TemplateView):
    template_name="article_add.html"
    form=None
    success_url="/"

    def get(self,request,*args,**kwargs):
        self.form=ArticleForm(initial={"creator":request.user})
        return super(ArticleUserCreate,self).get(request,*args,**kwargs)

    def get_context_data(self,**kwargs):
        context=super(ArticleUserCreate,self).get_context_data(**kwargs)
        context["form"]=self.form
        return context

    def post(self,request,*args,**kwargs):
        self.form=ArticleForm(request.POST,request.FILES)
        if self.form.is_valid():
            new_article=self.form.save(commit=False)
            new_article.creator=self.request.user
            new_article=self.form.save()
            new_article.create_article(
                creator=new_article.creator,
                content=new_article.content,
                community=None,
                g_image=new_article.g_image,
                comments_enabled=new_article.comments_enabled,
                status=new_article.status,
            )

            if request.is_ajax() :
                 html = render_to_string('generic/posts/article.html',{'object': new_article,'request': request})
                 return HttpResponse(html)
        else:
           return HttpResponseBadRequest()
        return super(ArticleUserCreate,self).get(request,*args,**kwargs)


class ArticleCommunityCreate(TemplateView):
    template_name="article_add_community.html"
    form=None
    success_url="/"

    def get(self,request,*args,**kwargs):
        self.form=ArticleForm()
        self.community = Community.objects.get(pk=self.kwargs["pk"])
        return super(ArticleCommunityCreate,self).get(request,*args,**kwargs)

    def get_context_data(self,**kwargs):
        context=super(ArticleCommunityCreate,self).get_context_data(**kwargs)
        context["form"]=self.form
        context["community"]=self.community
        return context

    def post(self,request,*args,**kwargs):
        self.form=ArticleForm(request.POST,request.FILES)
        self.community = Community.objects.get(pk=self.kwargs["pk"])
        if self.form.is_valid():
            new_article=self.form.save(commit=False)
            new_article.creator=self.request.user
            new_article.community=self.community
            new_article=self.form.save()

            if request.is_ajax() :
                 html = render_to_string('generic/posts/article.html',{'object': new_article,'request': request})
                 return HttpResponse(html)
        else:
           HttpResponseBadRequest()
        return super(ArticleCommunityCreate,self).get(request,*args,**kwargs)


class ArticleCommentCreateView(TemplateView):
    template_name = "generic/posts/article_comment.html"

    def post(self, request, *args, **kwargs):
        comment = self.request.POST.get('text')
        article = Article.objects.get(pk=post_pk)

        new_comment = article.comments.create(creator=request.user, text=comment)
        data = [
                {
                'commenter': new_comment.commenter.get_full_name(),
                "comment": new_comment.text,
                "comment_id": new_comment.pk,
                }
        ]
        return JsonResponse(data, safe=False)

        notification_handler(
            user, article.creator, Notification.ARTICLE_COMMENT, action_object=reply_article,
            id_value=str(post.uuid), key='social_update')

article/templates/article_add.html
{% load staticfiles %}
<style>
    .id_g_image input {
        display: none;
    }

    #image-holder {
        border: 2px dashed #FF0000;
        color: rgba(0, 0, 0, 0.8);
        padding: 10px;
        text-align: center;
        margin: 10px;
    }

    #image-holder:hover {
        cursor: pointer;
        margin: 9px;
    }

    #image-holder img {
        height: auto;
        width: 100%;
    }
</style>

<span class="article_fullscreen_hide">
  <img style="width:35px" src="{% static 'images/icons/close-24px.svg' %}" />
</span>

<br>
<h5 class="m-0">Добавление статьи</h5>
<br><br>

<form action="" id="FORM-ARTICLE" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label>Название статьи (обязательно)</label>
        <input type="text" required name="title" class="form-control" id="id_title">
    </div>
    <br>
    <div class="form-group">
        <div class="id_g_image">{{ form.g_image }}</div>
        <div id="image-holder">
            <h4 style="font-weight:bold;font-size:70px;color:#CECECE">обложка</h4>
            <p>Нажмите, чтобы добавить</p>

            <i style="">(обязательно)</i>

        </div>
    </div>
    <br>
    <div class="form-group">
        {{ form.content }}
    </div>
    <br>
    <div class="form-group ">
        <div class="custom-control custom-checkbox">
            <input type="checkbox" checked class="custom-control-input" name="comments_enabled" id="id_comments_enabled2">
            <label class="custom-control-label" for="id_comments_enabled2">Разрешить комментарии</label>
        </div>
    </div>
    <div class="respons_article"></div>
    <div class="card-footer">
        <button class="btn btn-secondary remove_form">Отмена</button>
        <button type="submit" id="article_post" class="btn btn-success float-right">Опубликовать</button>
    </div>
</form>

<script>
    var frm_art = $('#FORM-ARTICLE');
    $('#FORM-ARTICLE').submit(function(e) {
        e.preventDefault();
        CKEDITOR.instances.id_content.updateElement();
        $.ajax({
            type: frm_art.attr('method'),
            url: "{% url 'article_add_user' %}",
            data: new FormData($(frm_art)[0]),
            contentType: false,
            cache: false,
            processData: false,

            success: function(data) {
                if (data.error) {
                    console.log(data);
                    console.log(data.content);
                    console.log(data.image);
                    $(".respons_article").html(data.errors.content);
                } else {
                    $(".stream").prepend(data);
                    $('.article_fullscreen').hide();
                    $('#article_loader').empty();

                    $.toast({
                        heading: '{{ request.user.first_name }}',
                        text: 'Статья успешно создана!',
                        showHideTransition: 'fade',
                        icon: 'success',
                    })
                }
            },

            error: function(data) {

            }
        });
        return false;
    });
</script>
<script>
    var imageLoader = document.getElementById("id_g_image");
    var entrou = false;
    $("#image-holder").on("click", function() {
        $("#id_g_image").click();
    });

    $("#id_g_image").on("change", function() {
        if (!entrou) {
            var imgPath = $(this)[0].value;
            var extn = imgPath.substring(imgPath.lastIndexOf(".") + 1).toLowerCase();

            if (extn == "gif" || extn == "png" || extn == "jpg" || extn == "jpeg") {
                if (typeof FileReader != "undefined") {
                    var image_holder = $("#image-holder");
                    image_holder.empty();

                    var reader = new FileReader();
                    reader.onload = function(e) {
                        $img = $("<img />", {
                            id: "targetImageCrop",
                            src: e.target.result,
                            class: "thumb-image"
                        }).appendTo(image_holder);
                    };

                    image_holder.show();
                    reader.readAsDataURL($(this)[0].files[0]);
                }
            } else {
                this.value = null;
            }
        }
        entrou = true;
        setTimeout(function() {
            entrou = false;
        }, 1000);
    });
</script>
<script>
    $(".remove_form").click(function() {
        $('.article_fullscreen').hide();
        $('#article_loader').empty();
    });
</script>
<script>
    $('.article_fullscreen_hide').on('click', function() {
        $('.article_fullscreen').hide();
        $('#article_loader').empty();
    });
</script>

<script defer type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script defer type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

article/templates/article_add_community.html
{% load staticfiles %}
<style>
    .id_g_image input {
        display: none;
    }

    #image-holder {
        border: 2px dashed #FF0000;
        color: rgba(0, 0, 0, 0.8);
        padding: 10px;
        text-align: center;
        margin: 10px;
    }

    #image-holder:hover {
        cursor: pointer;
        margin: 9px;
    }

    #image-holder img {
        height: auto;
        width: 100%;
    }
</style>

<span class="article_fullscreen_hide">
  <img style="width:35px" src="{% static 'images/icons/close-24px.svg' %}" />
</span>

<br>
<h5 class="m-0">Добавление статьи</h5>
<br><br>

<form action="" id="FORM-ARTICLE" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label>Название статьи (обязательно)</label>
        <input type="text" required name="title" class="form-control" id="id_title">
    </div>
    <br>
    <div class="form-group">
        <div class="id_g_image">{{ form.g_image }}</div>
        <div id="image-holder">
            <h4 style="font-weight:bold;font-size:70px;color:#CECECE">обложка</h4>
            <p>Нажмите, чтобы добавить</p>

            <i style="">(обязательно)</i>

        </div>
    </div>
    <br>
    <div class="form-group">
        {{ form.content }}
    </div>
    <br>
    <div class="form-group ">
        <div class="custom-control custom-checkbox">
            <input type="checkbox" checked class="custom-control-input" name="comments_enabled" id="id_comments_enabled2">
            <label class="custom-control-label" for="id_comments_enabled2">Разрешить комментарии</label>
        </div>
    </div>
    <div class="respons_article"></div>
    <div class="card-footer">
        <button class="btn btn-secondary remove_form">Отмена</button>
        <button type="submit" id="article_post" class="btn btn-success float-right">Опубликовать</button>
    </div>
</form>

<script>
    var frm_art = $('#FORM-ARTICLE');
    $('#FORM-ARTICLE').submit(function(e) {
        e.preventDefault();
        CKEDITOR.instances.id_content.updateElement();
        $.ajax({
            type: frm_art.attr('method'),
            url: "{% url 'article_add_community' community.pk %}",
            data: new FormData($(frm_art)[0]),
            contentType: false,
            cache: false,
            processData: false,
            success: function(data) {
                    $(".stream").prepend(data);
                    $('.article_fullscreen').hide();
                    $('#article_loader').empty();
                    $.toast({
                        heading: '{{ request.user.first_name }}',
                        text: 'Статья успешно создана!',
                        showHideTransition: 'fade',
                        icon: 'success',
                    })
            },
            error: function(data) {
              $.toast({
                  heading: '{{ request.user.first_name }}',
                  text: 'Для публикации статьи нужно указать название, изображение, содержание',
                  showHideTransition: 'fade',
                  icon: 'error'
              })
            }
        });
        return false;
    });
</script>
<script>
    var imageLoader = document.getElementById("id_g_image");
    var entrou = false;
    $("#image-holder").on("click", function() {
        $("#id_g_image").click();
    });

    $("#id_g_image").on("change", function() {
        if (!entrou) {
            var imgPath = $(this)[0].value;
            var extn = imgPath.substring(imgPath.lastIndexOf(".") + 1).toLowerCase();

            if (extn == "gif" || extn == "png" || extn == "jpg" || extn == "jpeg") {
                if (typeof FileReader != "undefined") {
                    var image_holder = $("#image-holder");
                    image_holder.empty();

                    var reader = new FileReader();
                    reader.onload = function(e) {
                        $img = $("<img />", {
                            id: "targetImageCrop",
                            src: e.target.result,
                            class: "thumb-image"
                        }).appendTo(image_holder);
                    };

                    image_holder.show();
                    reader.readAsDataURL($(this)[0].files[0]);
                }
            } else {
                this.value = null;
            }
        }
        entrou = true;
        setTimeout(function() {
            entrou = false;
        }, 1000);
    });
</script>
<script>
    $(".remove_form").click(function() {
        $('.article_fullscreen').hide();
        $('#article_loader').empty();
    });
</script>
<script>
    $('.article_fullscreen_hide').on('click', function() {
        $('.article_fullscreen').hide();
        $('#article_loader').empty();
    });
</script>

<script defer type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script defer type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

article/templates/article_detail.html
{% load staticfiles humanize liked_user %}

<div class="card mb-4 infinite-item" style="display: block;" item-id="{{ object.uuid }}">
    <span class="article_fullscreen_hide">
      <img style="width:35px" src="{% static 'images/icons/close-24px.svg' %}" />
    </span>
    {% include 'generic/posts/card_header.html' %}

    <div class="card-body">
        <h2 class="">{{ object.article.title }}</h2>
        <br><br>
        <figure class="">
            {% if object.article.g_image %}
            <img src="{{ object.article.g_image.url }}" alt="">
            {% else %}
            <img src="{% static 'images/no-image.jpg' %}" />
            {% endif %}
        </figure>
        <div class="container">
            <br><br>
            {{ object.article.content|safe }}

        </div>
    </div>

    {% include 'generic/posts/info.html' %}
</div>

<script>
    $('.article_fullscreen_hide').on('click', function() {
        $('.article_fullscreen').hide();
        $('#article_loader').empty();
    });
</script>

article/templates/article_hard_add.html
{% load staticfiles %}
<script src="{% static 'scripts/jquery.js' %}" type="text/javascript"></script>

<span class="activefullscreen_hide2">Х</span>
<form action="" id="FORM-POST1" method="post">
  {% csrf_token %}
    {{ form_hard.content_hard }}
    <div class="card-footer">
      <button class="btn btn-secondary remove_form">Отмена</button>
      <button type="submit" class="btn btn-success float-right">Опубликовать</button>
   </div>
</form>

<script defer src="/static/scripts/jquery.toast.min.js" type="text/javascript"></script>
<script type="text/javascript">
    var frm = $('#FORM-POST1');
    frm.submit(function () {
      CKEDITOR.instances.id_content_hard.updateElement();
        $.ajax({
            type: frm.attr('method'),
            url: "{% url 'article_add_hard_user' %}",
            data: frm.serialize(),
            success: function (data) {
              $(".stream").prepend(data);
              $('#article_create').empty();
              $.toast({
                  heading: '{{ request.user.first_name }}',
                  text: 'Статья успешно создана!',
                  showHideTransition: 'fade',
                  icon: 'success'
              })
            },
            error: function(data) {
                $("#hack").html("Возникла непредвидинная ошибка!!");
            }
        });
        return false;
    });
</script>
<script>
  $( ".remove_form" ).click(function(){
    $('.activefullscreen2').hide();
    $('#article_loader').empty();
  });
</script>
<script>
  $('.activefullscreen_hide2').on('click', function () {
  	 $('.activefullscreen2').hide();
  	 $('#article_loader').empty();
  });
</script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

article/templates/article_like_window.html
{% load liked_user staticfiles %}

{% if article_like.votes.likes.all %}
<div class="like_pop" style="margin:15px">
  <span>Оценили: {{ article_like.votes.likes.count }} {{ article_like.votes.likes.count|rupluralize:"человек,человека,людей" }}</span>
  <br><br>
  <span style="display: flex;">
    {% for heart in article_like.votes.likes.all %}
    <a href="{% url 'user' pk=heart.user.pk %}" class="ajax" style="padding-right:10px">
      <figure style="margin: 0;">
        {% if heart.user.profile.avatar %}
          <img src="{{ heart.user.profile.avatar.url }}" style="border-radius: 50px;width:50px;" alt="image">
          {% else %}
          <img src="{% static 'images/user.png' %}" alt="image" style="border-radius: 50px;width:50px;">
          {% endif %}
      </figure>
      {{ heart.user.first_name }}
    </a>
    {% endfor %}
  </span>
</div>
{% endif %}