main/urls.py
from django.conf.urls import url
from main.views import (
						MainPageView,
						ComingView,
						ReactView,
						CommentReactView,
						CommentListView,
						post_comment,
						post_comment_react,
						comment_un_react,
						ReactUserCreate,
						un_react,
						reply_comment)
from django.contrib.auth.decorators import login_required


urlpatterns = [
	url(r'^$', ComingView.as_view(), name="coming"),
	url(r'^main/$', MainPageView.as_view(), name="main"),
	url(r'^main/react_window/(?P<pk>\d+)/$', ReactView.as_view(), name='react_window'),
	url(r'^main/comment/(?P<uuid>[0-9a-f-]+)/$', CommentListView.as_view(), name='get_comment'),
	url(r'^main/comment_react/$', post_comment_react, name='post_comment_react'),
	url(r'^main/comment_un_react/$', comment_un_react, name='comment_un_react'),
	url(r'^main/react/(?P<uuid>[0-9a-f-]+)/(?P<pk>\d+)/$', ReactUserCreate.as_view(), name='post_react'),
	url(r'^main/un_react/$', un_react, name='un_react'),
    url(r'^main/post-comment/$', post_comment, name='post_comment'),
    url(r'^main/reply-comment/$', reply_comment, name='reply_comment'),
	url(r'^main/comment_react_window/(?P<pk>\d+)/$', CommentReactView.as_view(), name='comment_react_window'),
]

tr/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView, RedirectView
from django.contrib.auth.decorators import login_required
from ckeditor_uploader import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include ('main.urls')),

    url(r'^logout/$', auth_views.LogoutView.as_view(template_name="account/logout.html"), name='logout'),
    url(r'^signup/$', TemplateView.as_view(template_name="main/auth.html"),
        name='signup'),
    url(r'^email-verification/$',
        TemplateView.as_view(template_name="account/email_verification.html"),
        name='email-verification'),
    url(r'^login/$', TemplateView.as_view(template_name="account/login.html"),
        name='login'),
    url(r'^password-reset/$',TemplateView.as_view(template_name="account/password_reset.html"),
        name='password-reset'),
    url(r'^password-reset/confirm/$',TemplateView.as_view(template_name="account/password_reset_confirm.html"),
        name='password-reset-confirm'),
     url(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        TemplateView.as_view(template_name="password_reset_confirm.html"),
        name='password_reset_confirm'),
    url(r'^password-change/$',TemplateView.as_view(template_name="account/password_change.html"),
        name='password-change'),

    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^rest-auth/registration/', include('rest_auth.registration.urls')),
    url(r'^account/', include('allauth.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^follows/', include('follows.urls')),
    url(r'^invitations/', include('invitations.urls')),
    url(r'^communities/', include('communities.urls')),
    url(r'^moderation/', include('moderation.urls')),
    url(r'^notifications/', include('notifications.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^frends/', include('frends.urls')),
    url(r'^chat/', include('chat.urls')),
    url(r'^gallery/', include('gallery.urls')),
    url(r'^article/', include('article.urls')),
    url(r'^goods/', include('goods.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/forms.py
from django import forms
from main.models import ItemComment

class CommentForm(forms.ModelForm):

	class Meta:
		model = ItemComment
		fields = ['text']

users/forms.py
from django import forms
from django.http import Http404
from django.contrib.auth.models import User
from .models import UserProfile
from django import forms


class GeneralUserForm(forms.ModelForm):
    first_name = forms.CharField(required=False,max_length=256,label='Имя')
    last_name = forms.CharField(required=False,max_length=256,label='Фамилия')

    class Meta:
        model = UserProfile
        fields = (
        'first_name',
        'last_name',
        'sity',
        'vk_url',
        'youtube_url',
        'facebook_url',
        'instagram_url',
        'twitter_url',
        'phone',
        )


class AboutUserForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = (
        'bio',
        )

class AvatarUserForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = (
        'avatar',
        )

main/views.py
from django.views.generic.base import TemplateView
from users.models import User
from main.models import Item, ItemComment, ItemReaction, ItemCommentReaction
from common.models import Emoji
from django.utils import timezone
from django.http import HttpResponse, HttpResponseBadRequest, JsonResponse
from main.forms import CommentForm
from django.template.loader import render_to_string
from django.views import View
from posts.models import Post
from django.views.generic import ListView
from generic.mixins import CategoryListMixin



class MainPageView(TemplateView):
	template_name=None
	def get(self,request,*args,**kwargs):
		if request.user.is_authenticated:
			self.template_name="main/mainpage.html"
		else:
			self.template_name="main/auth.html"
		return super(MainPageView,self).get(request,*args,**kwargs)

	def get_context_data(self,**kwargs):
		context=super(MainPageView,self).get_context_data(**kwargs)
		return context


class ComingView(TemplateView):
	template_name="main/coming.html"


class RepostUser(View):

	def post(self, request, *args, **kwargs):
		self.item = Item.objects.get(pk=self.kwargs["pk"])
		if self.item.parent:
			new_repost = Post.objects.create(creator=request.user, parent=self.item.parent, is_repost=True)
			return HttpResponse("репост репоста")
		else:
			new_repost = Post.objects.create(creator=request.user, parent=self.item, is_repost=True)
			return HttpResponse("репост item")


class ReactView(TemplateView):
	template_name="react_window.html"

	def get(self,request,*args,**kwargs):
		item = Item.objects.get(uuid=self.kwargs["uuid"])
		emoji = Emoji.objects.get(pk=self.kwargs["pk"])
		react = ItemComment.objects.filter(item=item, emoji=emoji)
		return super(ReactView,self).get(request,*args,**kwargs)

	def get_context_data(self,**kwargs):
		context=super(ReactView,self).get_context_data(**kwargs)
		context["react"]=self.react
		return context


class CommentReactView(TemplateView):
    template_name="comment_react_window.html"

    def get(self,request,*args,**kwargs):
        self.react_like = ItemComment.objects.get(pk=self.kwargs["pk"])
        return super(CommentReactView,self).get(request,*args,**kwargs)

    def get_context_data(self,**kwargs):
        context=super(CommentReactView,self).get_context_data(**kwargs)
        context["react_like"]=self.react_like
        return context


class CommentListView(View, CategoryListMixin):
	model=ItemComment

	def get(self,request,*args,**kwargs):
		item = Item.objects.get(uuid=self.kwargs["uuid"])
		comments = ItemComment.objects.filter(item=item, parent_comment=None).order_by("created")
		comments_html = render_to_string("generic/posts/comments.html", {"comments": comments,"parent": item})

		return JsonResponse({
	        "comments": comments_html,
	    })


class ReactUserCreate(View):
	model=ItemReaction

	def post(self,request,*args,**kwargs):
		item = Item.objects.get(uuid=self.kwargs["uuid"])
		emoji = Emoji.objects.get(pk=self.kwargs["pk"])
		new_react = ItemReaction.objects.create(item=item, created=timezone.now(), emoji=emoji, reactor=request.user)
		new_react.notification_react(request.user)
		html = render_to_string("generic/posts/emoji.html",{'react': new_react,'request': request})
		return JsonResponse(html, safe=False)


def post_comment(request):
	user = request.user
	text = request.POST['text']
	img = "frtyh"
	par = request.POST['parent']
	item = Item.objects.get(pk=par)
	text = text.strip()

	if len(text) > 0:
		new_comment = ItemComment.objects.create(item=item, text=text, commenter=request.user)
		html = render_to_string('generic/posts/parent_comment.html',{'comment': new_comment,'request': request})
		return JsonResponse(html, safe=False)
	else:
		return HttpResponseBadRequest()


def reply_comment(request):

    user = request.user
    text = request.POST['text']
    com = request.POST['comment']
    comment = ItemComment.objects.get(pk=com)
    text = text.strip()
    if len(text) > 0:
        new_comment = ItemComment.objects.create(text=text, commenter=request.user,parent_comment=comment)
        html = render_to_string('generic/posts/reply_comment.html',{'reply': new_comment,'request': request})
        return JsonResponse(html, safe=False)

        notification_handler(
            user, parent.creator, Notification.ARTICLE_REPLY_COMMENT, action_object=reply_article,
            id_value=str(com.id), key='social_update')

    else:
        return HttpResponseBadRequest()


def un_react(request):
	un_react = request.POST['emoji']
	par = request.POST['parent']
	item = Item.objects.get(pk=par)
	if item:
		un_react = ItemReaction.objects.get(item=item, emoji=un_react, reactor=request.user)
		un_react.delete()
		html = render_to_string('generic/posts/emoji.html',{'react': un_react,'request': request})
		return JsonResponse(html, safe=False)
	else:
		return HttpResponse("react не найден")



def post_comment_react(request):
	react = request.POST['emoji']
	com = request.POST['comment']
	comment = ItemComment.objects.get(pk=com)
	if comment:
		new_comment_react = ItemCommentReaction.objects.create(comment=comment, emoji=react, reactor=request.user)
		html = render_to_string('generic/posts/comment_emoji.html',{'comment_react': new_comment_react,'request': request})
		return JsonResponse(html, safe=False)
	else:
		return HttpResponse("react не найден")



def comment_un_react(request):
	un_react = request.POST['emoji']
	com = request.POST['comment']
	comment = ItemComment.objects.get(pk=com)
	if comment:
		un_react = ItemCommentReaction.objects.get(comment=comment, emoji=un_react, reactor=request.user)
		html = render_to_string('generic/posts/comment_emoji.html',{'comment_react': un_react,'request': request})
		return JsonResponse(html, safe=False)
	else:
		return HttpResponse("react не найден")


def post_update_interactions(request):
    data_point = request.POST['id_value']
    item = Item.objects.get(uuid=data_point)
    data = {'likes': item.count_likers(), 'dislikes': item.count_dislikers(), 'comments': item.count_thread()}
    return JsonResponse(data)

templates/main/auth.html
{% extends "base.html" %}
{% load staticfiles humanize %}
{% block title %}Рады Вас видеть | трезвый.рус{% endblock %}
{% block content %}

<div class="container-fluid h-100 h-sm-auto"">
            <div class=" row h-100 h-sm-auto">
    <div class="col-12 col-md-7 h-md-100  h-sm-auto order-1 order-md-1 bg-dark">
        <div class="carosel swiper-location-carousel h-100 h-sm-auto">
            <div data-pagination='{"el": ".swiper-pagination"}' data-space-between="0" data-slides-per-view="1" class="swiper-container swiper-init swiper-signin h-100">
                <div class="swiper-pagination"></div>
                <div class="swiper-wrapper">
                    <div class="swiper-slide text-center ">
                        <div class="background-img">
                            <img src="{% static 'images/banner.png' %}" alt="" class="w-auto float-right">
                        </div>
                        <div class="row align-items-center h-100 text-white">
                            <div class="col-10 col-md-8 col-lg-6 mx-auto my-4">
                                <h1 class="font-weight-light mb-4">Easy, Unique and Creative multipurpose template</h1>
                                <p>GoTRI-Mobile is very unique and flexible with large number of customized components. Get this now, share with beautiful world. </p>
                            </div>
                        </div>
                    </div>
                    <div class="swiper-slide text-center">
                        <div class="background-img"><img src="{% static 'images/banner2.png' %}" alt="" class="w-auto"></div>
                        <div class="row align-items-center h-100 text-white">
                            <div class="col-10 col-md-8 col-lg-6 mx-auto my-4">
                                <h1 class="font-weight-light mb-4">Save 1000s hours, Efforts and your own Money</h1>
                                <p>GoTRI has many more flexible unique component with very creative design you can save much more with this template.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-12 col-md-5 h-md-100  h-sm-auto order-2 order-md-2">
        <form action="{% url 'rest_login' %}" id="login_form" class="row align-items-center h-sm-auto">
            <div class="col-12">
                <h1 class="font-weight-light mb-3 mt-4 content-color-secondary text-left">Вход</h1>
                <div class="card mb-2">
                    <div class="card-body p-0">
                        <input type="email" name="email" class="form-control form-control-lg border-0" placeholder="Email">
                        <hr class="my-0">
                        <input type="password" name="password" class="form-control form-control-lg border-0" placeholder="Ваш пароль">
                    </div>
                </div>
                <small class="form-text text-muted login-response"></small>
                <div class="text-left mb-4">
                    <button type="submit" id="logg" class=" btn btn-primary pink-gradient">Войти</button>
                    <a href="" class="ajax" style="float:right;padding-top: 9px;">Забыли пароль?</a>
                </div>
            </div>
        </form>
        <br><br><br>
        <form action="{% url 'rest_register' %}" id="signup" class="row align-items-center h-sm-auto">

            <div class="col-12">
                <h1 class="font-weight-light mb-3 content-color-secondary text-left">Регистрация</h1>
                <div class="card mb-2">
                    <div class="card-body p-0">
                        <input type="text" name="first_name" id="id_first_name" class="form-control form-control-lg border-0" placeholder="Имя">
                        <hr class="my-0">
                        <input type="text" name="last_name" id="id_last_name" class="form-control form-control-lg border-0" placeholder="Фамилия">
                        <hr class="my-0">
                        <input type="text" name="email" class="form-control form-control-lg border-0" placeholder="Email">
                        <hr class="my-0">
                        <input type="password" name="password1" id="password1" class="form-control form-control-lg border-0" placeholder="Пароль">
                        <hr class="my-0">
                        <input type="password" name="password2" id="password2" class="form-control form-control-lg border-0" placeholder="Повторите пароль">
                    </div>
                </div>
                <br>
                <div class="col">
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" id="register_" checked onchange="document.getElementById('register_ajax').disabled = !this.checked;" class="custom-control-input">
                        <label class="custom-control-label" for="register_">
                            Я принимаю<a href=""> Правила сайта</a>.
                        </label>
                    </div>
                </div>
                <br>
                <small class="form-text text-muted reg-response"></small>
                <div class="text-left mb-4">
                    <button type="submit" class=" btn btn-primary pink-gradient" id="register_ajax">Создать аккаунт</button>
                </div>
            </div>
        </form>
    </div>
</div>
</div>



<script type="text/javascript">
    var error_response2 = function(data) {
        $('.reg-response').html("Что-то пошло не так... ");
    }
    var susccess_response2 = function(data) {

    }
    $().ready(function() {
        $('#register_ajax').click(function() {
            var form2 = $('#signup');
            $.post(form2.attr('action'), form2.serialize())
                .fail(function(data) {
                    error_response2(data);
                })
                .done(function(data) {
                    susccess_response(data);
                });
            return false;
        });
    });
</script>
<script type="text/javascript">
    var error_response = function(data) {
        $('.login-response').html("ошибка");
    }
    var susccess_response = function(data) {
        window.location = "{% url 'main' %}";
    }
    $().ready(function() {
        $('#logg').click(function() {
            var form3 = $('#login_form');
            $.post(form3.attr('action'), form3.serialize())
                .fail(function(data) {
                    error_response(data);
                    console.log(data);
                })
                .done(function(data) {
                    susccess_response(data);
                });
            return false;
        });
    });
</script>

{% endblock %}

templates/main/carusel.html
{% load staticfiles %}

<div class="container-fluid mt-4">
    <div class="carosel">
        <div data-space-between="0" data-slides-per-view="auto" class="swiper-container swiper-init swiper-story">
            <div class="swiper-wrapper">
                <div class="swiper-slide ">
                    <figure class="story-img"><img src="{% static 'images/news_small1.jpg' %}" alt=""></figure>
                    <div class="media">
                        <figure class="avatar avatar-30 mr-2">
                            <img src="{% static 'images/user1.png' %}" alt="Generic placeholder image">
                        </figure>
                        <div class="media-body ">
                            <p class="mb-0 text-hide-xs"><span class="content-color-primary">johnmcmohan</span>
                                <br><small>The large tigerroof</small></p>
                        </div>
                        <button class="btn btn-link btn-sm px-0">
                            <i class="material-icons text-danger icon-sm">favorite</i>
                            <br>
                            <small class="content-color-secondary">1.5k</small>
                        </button>
                    </div>
                </div>
                <div class="swiper-slide ">
                    <figure class="story-img"><img src="{% static 'images/news_small2.jpg' %}" alt=""></figure>
                    <div class="media">
                        <figure class="avatar avatar-30 mr-2">
                            <img src="{% static 'images/user2.png' %}" alt="Generic placeholder image">
                        </figure>
                        <div class="media-body ">
                            <p class="mb-0 text-hide-xs"><span class="content-color-primary">alizeechotali</span>
                                <br><small>All the awesomenes</small></p>
                        </div>
                        <button class="btn btn-link btn-sm px-0">
                            <i class="material-icons text-danger icon-sm">favorite</i>
                            <br>
                            <small class="content-color-secondary">2.5k</small>
                        </button>
                    </div>
                </div>
                <div class="swiper-slide ">
                    <figure class="story-img"><img src="{% static 'images/news_small3.jpg' %}" alt=""></figure>
                    <div class="media">
                        <figure class="avatar avatar-30 mr-2">
                            <img src="{% static 'images/user3.png' %}" alt="Generic placeholder image">
                        </figure>
                        <div class="media-body ">
                            <p class="mb-0 text-hide-xs"><span class="content-color-primary">chandufamous</span>
                                <br><small>Cityscape</small></p>
                        </div>
                        <button class="btn btn-link btn-sm px-0">
                            <i class="material-icons text-danger icon-sm">favorite</i>
                            <br>
                            <small class="content-color-secondary">1k</small>
                        </button>
                    </div>
                </div>
                <div class="swiper-slide ">
                    <figure class="story-img"><img src="{% static 'images/news_small4.jpg' %}" alt=""></figure>
                    <div class="media">
                        <figure class="avatar avatar-30 mr-2">
                            <img src="{% static 'images/user1.png' %}" alt="Generic placeholder image">
                        </figure>
                        <div class="media-body ">
                            <p class="mb-0 text-hide-xs"><span class="content-color-primary">johnmcmohan</span>
                                <br><small>The large tigerroof</small></p>
                        </div>
                        <button class="btn btn-link btn-sm px-0">
                            <i class="material-icons text-danger icon-sm">favorite</i>
                            <br>
                            <small class="content-color-secondary">1.5k</small>
                        </button>
                    </div>
                </div>
                <div class="swiper-slide ">
                    <figure class="story-img"><img src="{% static 'images/sunflowers-3640935_640.jpg' %}" alt=""></figure>
                    <div class="media">
                        <figure class="avatar avatar-30 mr-2">
                            <img src="{% static 'images/user2.png' %}" alt="Generic placeholder image">
                        </figure>
                        <div class="media-body ">
                            <p class="mb-0 text-hide-xs"><span class="content-color-primary">alizeechotali</span>
                                <br><small>All the awesomenes</small></p>
                        </div>
                        <button class="btn btn-link btn-sm px-0">
                            <i class="material-icons text-danger icon-sm">favorite</i>
                            <br>
                            <small class="content-color-secondary">2.5k</small>
                        </button>
                    </div>
                </div>
                <div class="swiper-slide ">
                    <figure class="story-img"><img src="{% static 'images/news_small1.jpg' %}" alt=""></figure>
                    <div class="media">
                        <figure class="avatar avatar-30 mr-2">
                            <img src="{% static 'images/user3.png' %}" alt="Generic placeholder image">
                        </figure>
                        <div class="media-body ">
                            <p class="mb-0 text-hide-xs"><span class="content-color-primary">chandufamous</span>
                                <br><small>Cityscape</small></p>
                        </div>
                        <button class="btn btn-link btn-sm px-0">
                            <i class="material-icons text-danger icon-sm">favorite</i>
                            <br>
                            <small class="content-color-secondary">1k</small>
                        </button>
                    </div>
                </div>
                <div class="swiper-slide ">
                    <figure class="story-img"><img src="{% static 'images/news_small2.jpg' %}" alt=""></figure>
                    <div class="media">
                        <figure class="avatar avatar-30 mr-2">
                            <img src="{% static 'images/user2.png' %}" alt="Generic placeholder image">
                        </figure>
                        <div class="media-body ">
                            <p class="mb-0 text-hide-xs"><span class="content-color-primary">alizeechotali</span>
                                <br><small>All the awesomenes</small></p>
                        </div>
                        <button class="btn btn-link btn-sm px-0">
                            <i class="material-icons text-danger icon-sm">favorite</i>
                            <br>
                            <small class="content-color-secondary">2.5k</small>
                        </button>
                    </div>
                </div>
                <div class="swiper-slide ">
                    <figure class="story-img"><img src="{% static 'images/news_small3.jpg' %}" alt=""></figure>
                    <div class="media">
                        <figure class="avatar avatar-30 mr-2">
                            <img src="{% static 'images/user3.png' %}" alt="Generic placeholder image">
                        </figure>
                        <div class="media-body ">
                            <p class="mb-0 text-hide-xs"><span class="content-color-primary">chandufamous</span>
                                <br><small>Cityscape</small></p>
                        </div>
                        <button class="btn btn-link btn-sm px-0">
                            <i class="material-icons text-danger icon-sm">favorite</i>
                            <br>
                            <small class="content-color-secondary">1k</small>
                        </button>
                    </div>
                </div>
                <div class="swiper-slide ">
                    <figure class="story-img"><img src="{% static 'images/news_small4.jpg' %}" alt=""></figure>
                    <div class="media">
                        <figure class="avatar avatar-30 mr-2">
                            <img src="{% static 'images/user1.png' %}" alt="Generic placeholder image">
                        </figure>
                        <div class="media-body ">
                            <p class="mb-0 text-hide-xs"><span class="content-color-primary">johnmcmohan</span>
                                <br><small>The large tigerroof</small></p>
                        </div>
                        <button class="btn btn-link btn-sm px-0">
                            <i class="material-icons text-danger icon-sm">favorite</i>
                            <br>
                            <small class="content-color-secondary">1.5k</small>
                        </button>
                    </div>
                </div>
                <div class="swiper-slide ">
                    <figure class="story-img"><img src="{% static 'images/sunflowers-3640935_640.jpg' %}" alt=""></figure>
                    <div class="media">
                        <figure class="avatar avatar-30 mr-2">
                            <img src="{% static 'images/user2.png' %}" alt="Generic placeholder image">
                        </figure>
                        <div class="media-body ">
                            <p class="mb-0 text-hide-xs"><span class="content-color-primary">alizeechotali</span>
                                <br><small>All the awesomenes</small></p>
                        </div>
                        <button class="btn btn-link btn-sm px-0">
                            <i class="material-icons text-danger icon-sm">favorite</i>
                            <br>
                            <small class="content-color-secondary">2.5k</small>
                        </button>
                    </div>
                </div>
                <div class="swiper-slide ">
                    <figure class="story-img"><img src="{% static 'images/news_small1.jpg' %}" alt=""></figure>
                    <div class="media">
                        <figure class="avatar avatar-30 mr-2">
                            <img src="{% static 'images/user3.png' %}" alt="Generic placeholder image">
                        </figure>
                        <div class="media-body ">
                            <p class="mb-0 text-hide-xs"><span class="content-color-primary">chandufamous</span>
                                <br><small>Cityscape</small></p>
                        </div>
                        <button class="btn btn-link btn-sm px-0">
                            <i class="material-icons text-danger icon-sm">favorite</i>
                            <br>
                            <small class="content-color-secondary">1k</small>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/main/coming.html
{% extends "base_coming.html" %}
{% load staticfiles humanize %}
{% block title %}Социальная сеть еще строится{% endblock %}
{% block meta %}
<meta property="og:url" content="http://xn--b1afgj5al1e.xn--p1acf/" />
<meta property="og:type" content="website" />
<meta property="og:title" content="" />
<meta property="og:image" content="http://xn--b1afgj5al1e.xn--p1acf{% static 'images/1.jpg' %}?r=qwert" />
{% endblock %}
<style>

</style>
{% block content %}

<div style="padding-bottom: 43px;background: linear-gradient(45deg, #292929 25%, transparent 25%, transparent 75%, #292929 75%), linear-gradient(45deg, #292929 25%, transparent 25%, transparent 75%, #292929 75%) 0.1875em 0.1875em, radial-gradient(at 50% 0, #484847, #090909);
background-size: 0.375em 0.375em, 0.375em 0.375em, 100% 100%;">


        <div class="container main-container h-100 h-sm-auto z-index-1 text-center text-white">
            <div class="row align-items-center h-100">
                <div class="col-12 mx-auto text-center">
                    <h1 class="text-white  mt-5">трезвый.рус</h1>
                    <h3 class="font-weight-light text-white">Будет строиться еще 20-40 дней</h3>

                    <div class="row">
                        <div class="col-12 col-sm-8 col-md-8 col-lg-8 m-auto text-white" style="font-size:25px;line-height:35px;">
                          <br><br>
                          <p>Социальная сеть будет допускать только нравственный, трезвый, добрый контент.
                          Здесь взрослые и дети не будут подвергаться информационному насилию, потреблять
                          деструктивные образы, заниматься деградацией и другими насаждаемыми пороками.
                          трезвый.рус должен будет помочь объединиться хорошим людям, продвигать хорошие товары
                          и достойные услуги, обеспечить нравственное инфопространство на долгое время, с гарантией
                          этого курса развития!
                          <br><br>
                          Это самый важный подход, однако всеми соц сетями он игнорируется.

                          <br><br>
                          Друзья, подписчики, мощная модерация и социальные инструменты, сообщества разного типа,
                          фотоальбомы, товары, статьи, записи, голосования. Лайки, дизлайки, репосты, комментарии и ответы,
                          все в режиме реального времени. Ленты новостей, мгновенные уведомления о событиях, и много сюрпризов.</p>

                            <br>

                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}