article/urls.py
from article.views import (
                            ArticleView,
                            ArticleUserCreate,
                            ArticleNewView,
                            ArticleDetailView,
                            ArticleCommunityCreate,
                        )
from django.conf.urls import url


urlpatterns = [
    url(r'^$', ArticleView.as_view(), name='articles'),
    url(r'^add/$', ArticleUserCreate.as_view(), name="article_add_user"),
    url(r'^add_community/(?P<pk>\d+)/$', ArticleCommunityCreate.as_view(), name="article_add_community"),
    url(r'^new/(?P<uuid>[0-9a-f-]+)/$', ArticleNewView.as_view(), name='article_new'),
    url(r'^detail/(?P<uuid>[0-9a-f-]+)/$', ArticleDetailView.as_view(), name='article_detail'),
]

communities/urls.py
from communities.views import (
                                CommunitiesView,
                                CommunityDetailView,
                                AllCommunities,
                                CommunityCreate,
                                CommunitiesCatsView,
                                CommunityItemView,
                                CommunityListView,
                                CommunityDetailReload,
                                GygView,
                                CommunityMembersView,
                            )
from django.conf.urls import url

urlpatterns = [
    url(r'^user/(?P<pk>\d+)/$', CommunitiesView.as_view(), name='communities'),
    url(r'^(?P<pk>\d+)/$', CommunityDetailView.as_view(), name='community_detail'),
    url(r'^reload/(?P<pk>\d+)/$', CommunityDetailReload.as_view(), name='community_detail_reload'),
    url(r'^all-communities/$', AllCommunities.as_view(), name='all_communities'),
    url(r'^add/$', CommunityCreate.as_view(), name="add_community"),
    url(r'^cat/(?P<order>\d+)/$',CommunitiesCatsView.as_view(), name="communities_cats"),
    url(r'^item/(?P<pk>\d+)/$', CommunityItemView.as_view(), name='community_item'),
    url(r'^list/(?P<pk>\d+)/$', CommunityListView.as_view(), name="community_item_list"),
    url(r'^gygyg/$', GygView.as_view(), name="community_ggg"),
    url(r'^(?P<pk>\d+)/members/$', CommunityMembersView.as_view(), name='community_members'),
]

posts/urls.py
from posts.views import (
                            PostsView,
                            PostDetailView,
                            PostUserCreate,
                            PostCommunityCreate,

                            RepostUserUser,
                            RepostUserCommunity,
                            RepostCommunityCommunity,
                            RepostCommunityUser,
                        )
from django.conf.urls import url



urlpatterns = [
    url(r'^$', PostsView.as_view(), name='posts'),
    url(r'^add_post/$', PostUserCreate.as_view(), name="post_add_user"),
    url(r'^add_post_community/(?P<pk>\d+)/$', PostCommunityCreate.as_view(), name="post_add_community"),
    url(r'^detail/(?P<uuid>[0-9a-f-]+)/$', PostDetailView.as_view(), name='post_detail'),

    url(r'^repost_user_user/(?P<uuid>[0-9a-f-]+)/$', RepostUserUser.as_view(), name="repost_user_user"),
    url(r'^repost_user_community/(?P<pk>\d+)/(?P<uuid>[0-9a-f-]+)/$', RepostUserCommunity.as_view(), name="repost_user_community"),
    url(r'^repost_community_community/(?P<pk>\d+)/(?P<uuid>[0-9a-f-]+)/$', RepostCommunityCommunity.as_view(), name="repost_community_community"),
    url(r'^repost_community_user/(?P<pk>\d+)/$', RepostCommunityUser.as_view(), name="repost_community_user"),
]

tr/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView, RedirectView
from django.contrib.auth.decorators import login_required
from ckeditor_uploader import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include ('main.urls')),

    url(r'^logout/$', auth_views.LogoutView.as_view(template_name="account/logout.html"), name='logout'),
    url(r'^signup/$', TemplateView.as_view(template_name="main/auth.html"),
        name='signup'),
    url(r'^email-verification/$',
        TemplateView.as_view(template_name="account/email_verification.html"),
        name='email-verification'),
    url(r'^login/$', TemplateView.as_view(template_name="account/login.html"),
        name='login'),
    url(r'^password-reset/$',TemplateView.as_view(template_name="account/password_reset.html"),
        name='password-reset'),
    url(r'^password-reset/confirm/$',TemplateView.as_view(template_name="account/password_reset_confirm.html"),
        name='password-reset-confirm'),
     url(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        TemplateView.as_view(template_name="password_reset_confirm.html"),
        name='password_reset_confirm'),
    url(r'^password-change/$',TemplateView.as_view(template_name="account/password_change.html"),
        name='password-change'),

    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^rest-auth/registration/', include('rest_auth.registration.urls')),
    url(r'^account/', include('allauth.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^follows/', include('follows.urls')),
    url(r'^invitations/', include('invitations.urls')),
    url(r'^communities/', include('communities.urls')),
    url(r'^moderation/', include('moderation.urls')),
    url(r'^notifications/', include('notifications.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^frends/', include('frends.urls')),
    url(r'^chat/', include('chat.urls')),
    url(r'^gallery/', include('gallery.urls')),
    url(r'^article/', include('article.urls')),
    url(r'^goods/', include('goods.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.utils import timezone
from pilkit.processors import ResizeToFill, ResizeToFit
from django.conf import settings
from imagekit.models import ProcessedImageField
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from posts.helpers import upload_to_post_image_directory, upload_to_post_directory
from django.contrib.postgres.indexes import BrinIndex
from main.models import Item
from rest_framework.exceptions import ValidationError


class Post(Item):
    text = models.TextField(max_length=settings.POST_MAX_LENGTH, blank=False, null=True, verbose_name="Текст")


    @classmethod
    def create_post(cls, creator, text=None, community=None, comments_enabled=None, video=None,
                    is_draft=False, good=None, status= None, doc=None, question=None):

        if not text:
            raise ValidationError('Нужно ввести текст или прикрепить фото')
        else:
            post = Post.objects.create(
                                        creator=creator,
                                        text=text,
                                        community=community,
                                        comments_enabled=comments_enabled,
                                        status = status,
                                    )
            channel_layer = get_channel_layer()
            payload = {
                    "type": "receive",
                    "key": "additional_post",
                    "actor_name": post.creator.get_full_name()
                }
            async_to_sync(channel_layer.group_send)('notifications', payload)
        return post

    def is_text_only_post(self):
        return self.has_text() and not self.has_image()

    def has_text(self):
        if hasattr(self, 'text'):
            if self.text:
                return True
        return False

    def has_image(self):
        if hasattr(self, 'image'):
            if self.image:
                return True
        return False

    def get_first_image(self):
        return self.image.first()

    def is_draft(self):
        return self.status == Post.STATUS_DRAFT

    def is_empty(self):
        return not self.text and not hasattr(self, 'image') and not hasattr(self, 'video') and not self.has_media()

    def has_image(self):
        return self.image.exists()

    def delete(self, *args, **kwargs):
        self.delete_image()
        super(Post, self).delete(*args, **kwargs)

    def delete_image(self):
        if self.has_image():
            delete_file_field(self.image.image)

    def soft_delete(self):
        self.delete_notifications()
        for comment in self.comments.all().iterator():
            comment.soft_delete()
        self.is_deleted = True
        self.save()

    class Meta:
        ordering=["-created"]
        verbose_name="Запись"
        verbose_name_plural="Записи"

    def __str__(self):
        return self.creator.get_full_name()


class PostUserMention(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, db_index=False, on_delete=models.CASCADE, related_name='post_mentions', verbose_name="Упоминаемый")
    post = models.ForeignKey(Post, db_index=False, on_delete=models.CASCADE, related_name='user_mentions', verbose_name="Запись")


class PostDoc(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_doc', null=True, verbose_name="Документ")
    doc = models.FileField(upload_to=upload_to_post_directory, verbose_name="Документ")

article/forms.py
from article.models import Article
from django import forms


class ArticleForm(forms.ModelForm):

	class Meta:
		model = Article
		fields = ['title', 'content', 'g_image', 'comments_enabled']

communities/forms.py
from communities.models import Community
from django import forms


class CommunityForm(forms.ModelForm):

	class Meta:
		model = Community
		fields = [	'name',
					'type',
					'category',
					'id',
				]

posts/forms.py
from posts.models import Post
from django import forms

class PostForm(forms.ModelForm):

	class Meta:
		model = Post
		fields = ['text', 'status', 'comments_enabled']


class PostCommunityForm(forms.ModelForm):

	class Meta:
		model = Post
		fields = ['text', 'status', 'comments_enabled']

article/views.py
from django.views.generic.base import TemplateView
from article.forms import ArticleForm
from users.models import User
from django.template.loader import render_to_string
from article.models import Article
from django.urls import reverse_lazy
from django.http import HttpResponse, HttpResponseBadRequest
from generic.mixins import CategoryListMixin
from communities.models import Community


class ArticleView(TemplateView):
    template_name="articles.html"


class ArticleNewView(CategoryListMixin, TemplateView):
    model=Article
    template_name="article.html"

    def get(self,request,*args,**kwargs):
        self.article = Article.objects.get(uuid=self.kwargs["uuid"])
        self.article.views += 1
        self.article.save()
        return super(ArticleNewView,self).get(request,*args,**kwargs)

    def get_context_data(self,**kwargs):
        context=super(ArticleNewView,self).get_context_data(**kwargs)
        context["object"]=self.article
        return context

class ArticleDetailView(CategoryListMixin, TemplateView):
    model=Article
    template_name="article_detail.html"

    def get(self,request,*args,**kwargs):
        self.article = Article.objects.get(uuid=self.kwargs["uuid"])
        self.article.views += 1
        self.article.save()
        return super(ArticleDetailView,self).get(request,*args,**kwargs)

    def get_context_data(self,**kwargs):
        context=super(ArticleDetailView,self).get_context_data(**kwargs)
        context["object"]=self.article
        return context


class ArticleUserCreate(TemplateView):
    template_name="article_add.html"
    form=None
    success_url="/"

    def get(self,request,*args,**kwargs):
        self.form=ArticleForm(initial={"creator":request.user})
        return super(ArticleUserCreate,self).get(request,*args,**kwargs)

    def get_context_data(self,**kwargs):
        context=super(ArticleUserCreate,self).get_context_data(**kwargs)
        context["form"]=self.form
        return context

    def post(self,request,*args,**kwargs):
        self.form=ArticleForm(request.POST,request.FILES)
        if self.form.is_valid():
            new_article=self.form.save(commit=False)
            new_article.creator=self.request.user
            new_article=self.form.save()
            new_article.create_article(
                creator=new_article.creator,
                content=new_article.content,
                community=None,
                g_image=new_article.g_image,
                comments_enabled=new_article.comments_enabled,
                status=new_article.status,
            )

            if request.is_ajax() :
                 html = render_to_string('generic/posts/article.html',{'object': new_article,'request': request})
                 return HttpResponse(html)
        else:
           return HttpResponseBadRequest()
        return super(ArticleUserCreate,self).get(request,*args,**kwargs)


class ArticleCommunityCreate(TemplateView):
    template_name="article_add_community.html"
    form=None
    success_url="/"

    def get(self,request,*args,**kwargs):
        self.form=ArticleForm()
        self.community = Community.objects.get(pk=self.kwargs["pk"])
        return super(ArticleCommunityCreate,self).get(request,*args,**kwargs)

    def get_context_data(self,**kwargs):
        context=super(ArticleCommunityCreate,self).get_context_data(**kwargs)
        context["form"]=self.form
        context["community"]=self.community
        return context

    def post(self,request,*args,**kwargs):
        self.form=ArticleForm(request.POST,request.FILES)
        self.community = Community.objects.get(pk=self.kwargs["pk"])
        if self.form.is_valid():
            new_article=self.form.save(commit=False)
            new_article.creator=self.request.user
            new_article.community=self.community
            new_article=self.form.save()

            if request.is_ajax() :
                 html = render_to_string('generic/posts/article.html',{'object': new_article,'request': request})
                 return HttpResponse(html)
        else:
           HttpResponseBadRequest()
        return super(ArticleCommunityCreate,self).get(request,*args,**kwargs)


class ArticleCommentCreateView(TemplateView):
    template_name = "generic/posts/article_comment.html"

    def post(self, request, *args, **kwargs):
        comment = self.request.POST.get('text')
        article = Article.objects.get(pk=post_pk)

        new_comment = article.comments.create(creator=request.user, text=comment)
        data = [
                {
                'commenter': new_comment.commenter.get_full_name(),
                "comment": new_comment.text,
                "comment_id": new_comment.pk,
                }
        ]
        return JsonResponse(data, safe=False)

        notification_handler(
            user, article.creator, Notification.ARTICLE_COMMENT, action_object=reply_article,
            id_value=str(post.uuid), key='social_update')

generic/controllers.py
from django.views.generic.base import View

class PageNumberView(View):
	def get(self,request,*args,**kwargs):
		try:
			self.sort=self.request.GET["sort"]
		except KeyError:
			self.sort="0"
		try:
			self.order=self.request.GET["order"]
		except KeyError:
			self.order="A"
		try:
			self.search=self.request.GET["search"]
		except KeyError:
			self.search=""
		try:
			self.tag=self.request.GET["tag"]
		except KeyError:
			self.tag=""
		return super(PageNumberView,self).get(request,*args,**kwargs)

	def post(self,request,*args,**kwargs):
		try:
			pn=request.GET["page"]
		except KeyError:
			pn = "1"
		self.success_url=self.success_url + "?page=" + pn
		try:
			self.success_url=self.success_url+"&search="+request.GET["search"]
		except KeyError:
			pass
		try:
			self.success_url=self.success_url+"&tag="+request.GET["tag"]
		except KeyError:
			pass

		return super(PageNumberView,self).post(request,*args,**kwargs)

templates/generic/community/article.html
{% load staticfiles humanize liked_user %}

<div class="card mb-4 infinite-item" item-id="{{ object.uuid }}">
    {% include 'generic/community/card_header.html' %}

    <div class="card-body article_detail" data-id="{{ object.uuid }}" style="cursor:pointer">
         <div class="jumbotron mb-4 bg-dark text-center has-background-img position-relative box-shadow">
             <div class="row align-items-center no-gutters">
                    <figure class="background-img">
                      {% if object.article.g_image %}
                        <img class="lazyload" data-src="{{ object.article.g_image.url }}" alt="">
                      {% else %}
                        <img class="lazyload" data-src="{% static 'images/no-image.jpg' %}" />
                      {% endif %}
                    </figure>
                    <div class="container">
                      <i class="figure avatar120 mr-0 fa fa-gift rounded-circle bg-none text-white border-white "></i>
                      <br>
                      <h2 class="text-white">{{ object.article.title}}</h2>
                      <p class="lead text-white">Автор {{ object.creator.get_full_name }}</p>
                      <hr class="my-3">
                      <a class="btn btn-primary" role="button">Читать</a>
                    </div>
            </div>
        </div>
    </div>

    {% include 'generic/community/info.html' %}
 </div>

templates/generic/community/card_header.html
{% load staticfiles humanize %}

<div class="card-header">
    <div class="media">
      <a href="{% url 'community_detail' pk=object.community.pk %}" class="ajax">
        <figure>
          {% if object.community.avatar %}
            <img src="{{ object.community.avatar.url }}" style="border-radius: 50px;width:40px;" alt="image">
          {% else %}
            <img style="width:50px;width:50px;width:50px;border:#6C757D solid 1px;border-radius:40px;padding:5px;" src="{% static 'images/icons/group-24px.svg' %}" />
          {% endif %}
        </figure>
      </a>
        <div class="media-body">
            <h6 class="mb-0">
              <a href="{% url 'community_detail' pk=object.community.pk %}" class="ajax">
                {{ object.community.name }} &nbsp;
              </a>
              <span class="is_fixed" style="color: #888888;font-size: 13px;{% if not object.is_fixed %}display:none;{% endif %}">закреплено</span>
            </h6>
            <p class="mb-0">{{ object.created|naturaltime }}</p>
        </div>

        <a style="cursor:pointer" class="icon-circle icon-30 react">
            <img style="width:22px" src="{% static 'images/icons/react-24px.svg' %}" />
        </a>
        &nbsp;
        <span class="react_window">

        <div class="react_pop" style="margin:15px">
          {% if emojies_1 %}
          <span style="display: flex;flex-wrap: wrap;width: 180px;">
            {% for object in emojies_2 %}
            <span data-id="{{ object.id }}" class="emoji" style="padding:6px;cursor:pointer" title="{{ object.keyword }}">
              <figure style="margin: 0;">
                {% if object.image %}
                  <img src="{{ object.image.url }}" style="border-radius: 50px;width:23px;" alt="emoji">
                  {% endif %}
              </figure>
            </span>
            {% endfor %}
            <br><br><br>

            {% for object in emojies_1 %}
            <span data-id="{{ object.id }}" class="emoji" style="padding:6px;cursor:pointer" title="{{ object.keyword }}">
              <figure style="margin: 0;">
                {% if object.image %}
                  <img src="{{ object.image.url }}" style="border-radius: 50px;width:23px;" alt="emoji">
                  {% endif %}
              </figure>
            </span>
            {% endfor %}
          </span>
          {% endif %}
        </div>

      </span>
        <div class="dropdown d-inline-block">
            <a style="cursor:pointer" class="icon-circle icon-30 dropdown-toggle caret-none" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <img style="width:22px" src="{% static 'images/icons/more_vert-24px.svg' %}" />
            </a>
            <div class="dropdown-menu dropdown-menu-right">
              {% if request.user == object.creator or staff %}
                <span data-id="{{ object.pk }}" style="cursor:pointer" class="dropdown-item remove">Удалить запись</span>
                <span data-action="item_update" style="cursor:pointer" class="dropdown-item">Редактировать</span>
                <span data-id="{{ object.pk }}">
                  {% if object.is_fixed %}
                  <span style="cursor:pointer" class="dropdown-item unfixed">Открепить</span>
                  {% else %}
                  <span style="cursor:pointer" class="dropdown-item fixed">Закрепить</span>
                  {% endif %}
                </span>
                <span data-action="item_check_comment" style="cursor:pointer" class="dropdown-item">Выключить комментарии</span>
              {% else %}
                <span data-actiond="item_bad" class="dropdown-item">Пожаловаться</span>
              {% endif %}
            </div>
        </div>
    </div>
</div>

templates/generic/community/emoji.html
{% load liked_user staticfiles %}

<span class="react_btn" style="margin-right:5px;cursor:pointer">
  <img style="width:22px;" src="{{ react.emoji.image.url }}">
  <span data-count="react">{{ react.count }}</span>
</span>

<span class="reaction_window">
<div style="margin:15px">
  <span>{{ react.count }} {{ react.count|rupluralize:"реакция,реакции,реакций" }}</span>
  <br><br>
  <span style="display: flex;">
    {% for heart in object.reactions.get_reactor %}
    <a href="{% url 'user' pk=heart.pk %}" class="ajax" style="padding-right:10px">
      <figure style="margin: 0;">
        {% if heart.profile.avatar %}
          <img src="{{ heart.profile.avatar.url }}" style="border-radius: 50px;width:50px;" alt="image">
          {% else %}
          <img src="{% static 'images/user.png' %}" alt="image" style="border-radius: 50px;width:50px;">
          {% endif %}
      </figure>
      {{ heart.first_name }}
    </a>
    {% endfor %}
  </span>
</div>
</span>

templates/generic/community/parent_comment.html
{% load staticfiles humanize liked_user %}

<div class="media" comment-id="{{ comment.id }}">
    <figure>
        {% if comment.commenter.profile.avatar %}
          <img src="{{ comment.commenter.profile.avatar.url }}" class="pull-left" style="border-radius:50%;width:30px;" alt="User Image" class="user-image">
        {% else %}
          <img src="{% static 'images/user.png' %}" class="pull-left" style="border-radius:50%;width:30px;" alt="No Profile Picture" />
        {% endif %}
    </figure>
    <div class="media-body">
        <h5 class="mt-0"><span class="commenter_first_name">{{ comment.commenter.first_name }}</span> {{ comment.commenter.last_name }}
            <small class="text-muted float-right">{{ comment.created|naturaltime }}</small>
        </h5>
        <p>{{ comment.text|safe }}</p>

        <div class="border-top py-2">
            <div class="row" style="color: rgba(255, 255, 255, 0.65);">
                <div class="col">

                    <span class="comment_react_window">
                        {% if comment.votes.dislikes.all %}
                        <div class="comment_dislike_pop" style="margin:15px">
                            <span>Не оценили: {{ comment.votes.dislikes.count }} {{ comment.votes.dislikes.count|rupluralize:"человек,человека,людей" }}</span>
                            <br><br>
                            <span style="display: flex;">
                                {% for sheet in comment.votes.dislikes.all %}
                                <a href="{% url 'user' pk=sheet.user.pk %}" class="ajax" style="padding-right:10px">
                                    <figure style="margin: 0;">
                                        {% if sheet.user.profile.avatar %}
                                        <img src="{{ sheet.user.profile.avatar.url }}" style="border-radius: 50px;width:50px;" alt="image">
                                        {% else %}
                                        <img src="{% static 'images/user.png' %}" alt="image" style="border-radius: 50px;width:50px;">
                                        {% endif %}

                                    </figure>
                                    {{ sheet.user.first_name }}
                                </a>
                                {% endfor %}
                            </span>
                        </div>
                        {% endif %}
                    </span>

                    &nbsp;&nbsp;
                    <span class="commenter_first_name" style="display:none">{{ comment.commenter.first_name }}</span>
                    <span class="content-color-secondary reply_comment" style="font-size:15px;cursor:pointer">
                        ответить
                    </span>

                    <div class="border-top reply_comment_form" style="margin-top:10px;display:none">
                        <form action="" method="post" class="replyComment_form">
                            {% csrf_token %}
                            <div class="row no-gutters">
                                <input type="hidden" name="comment" value="{{ comment.id }}">
                                <input type="hidden" name="parent" value="{{ parent.id }}">
                                <div class="col">
                                    <div class="input-group input-group-sm">
                                        <textarea id="id_text" name="text" class="form-control text-comment form-control-rounded"></textarea>
                                        <button class="btn btn-outline-primary btn-rounded btn-sm ml-2 replyComment" type="button">
                                          <img style="width:25px" src="{% static 'images/icons/send-24px.svg' %}" />
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>

                    </div>

                    <br><br>
                    <span class="stream_reply_comments">
                      {% for reply in comment.get_replies %}
                        {% include 'generic/community/reply_comment.html' with reply=reply  %}
                      {% endfor %}
                    </span>

                </div>
            </div>
        </div>
    </div>
</div>

templates/generic/community/post.html
{% load staticfiles humanize liked_user %}
<div class="card mb-4 infinite-item" item-id="{{ object.uuid }}">

    {% include 'generic/community/card_header.html' %}

    {% if object.is_repost %}
    {% include 'generic/community/repost.html' %}
    {% endif %}

    <div class="card-body fullscreen" data-id="{{ object.pk }}" style="cursor:pointer">
      {% if object.post.text %}
        <p class="">{{ object.post.text|linebreaks }}</p>
      {% endif %}
      {% if object.post.image %}
        <p class="">{{ object.post.image.url }}</p>
      {% endif %}
      {% if object.post.doc %}
        <p class="">{{ object.post.doc }}</p>
      {% endif %}
    </div>

    {% include 'generic/community/info.html' %}
</div>

templates/generic/community/reply_comment.html
{% load staticfiles humanize liked_user %}

<div class="media " reply-id="{{ reply.id }}">
    <figure>
        {% if reply.commenter.profile.avatar %}
          <img src="{{ reply.commenter.profile.avatar.url }}" class="pull-left" style="border-radius:50%;width:30px;" alt="User Image" class="user-image">
        {% else %}
          <img src="{% static 'images/user.png' %}" class="pull-left" style="border-radius:50%;width:30px;" alt="No Profile Picture" />
        {% endif %}
    </figure>
    <div class="media-body">
        <h5 class="mt-0"><span class="commenter_first_name">{{ reply.commenter.first_name }}</span> {{ reply.commenter.last_name }}
            <small class="text-muted float-right">{{ reply.created|naturaltime }}</small>
        </h5>
        <p>{{ reply.text|safe }}</p>

        <div class="border-top py-2">
            <div class="row" style="color: rgba(255, 255, 255, 0.65);">
                <div class="col">

                    <span class="comment_react_window">
                        {% if reply.votes.dislikes.all %}
                        <div class="comment_dislike_pop" style="margin:15px">
                            <span>Не оценили: {{ reply.votes.dislikes.count }} {{ reply.votes.dislikes.count|rupluralize:"человек,человека,людей" }}</span>
                            <br><br>
                            <span style="display: flex;">
                                {% for sheet in reply.votes.dislikes.all %}
                                <a href="{% url 'user' pk=sheet.user.pk %}" class="ajax" style="padding-right:10px">
                                    <figure style="margin: 0;">
                                        {% if sheet.user.profile.avatar %}
                                        <img src="{{ sheet.user.profile.avatar.url }}" style="border-radius: 50px;width:50px;" alt="image">
                                        {% else %}
                                        <img src="{% static 'images/user.png' %}" alt="image" style="border-radius: 50px;width:50px;">
                                        {% endif %}

                                    </figure>
                                    {{ sheet.user.first_name }}
                                </a>
                                {% endfor %}
                            </span>
                        </div>
                        {% endif %}
                    </span>

                    &nbsp;&nbsp;
                    <span class="commenter_first_name" style="display:none">{{ comment.commenter.first_name }}</span>
                    <span class="content-color-secondary reply_comment" data-id="{{ reply.id }}" style="font-size:15px;cursor:pointer">
                        ответить
                    </span>

                    <div class="border-top reply_comment_form" style="margin-top:10px;display:none">
                        <form action="" method="post" class="replyParentComment_button">
                            {% csrf_token %}
                            <div class="row no-gutters">
                                <input type="hidden" name="comment" value="{{ comment.id }}">
                                <input type="hidden" name="parent" value="{{ parent.id }}">
                                <div class="col" style="left: -30px;">
                                    <div class="input-group input-group-sm" style="width: 114%;">
                                        <textarea id="id_text" name="text" class="form-control text-comment form-control-rounded"></textarea>
                                        <button class="btn btn-outline-primary btn-rounded btn-sm ml-2 replyParentComment" type="button">
                                          <img style="width:22px" src="{% static 'images/icons/send-24px.svg' %}" />
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>